<?php

namespace App\Controller\Web\Pdf;

use App\Entity\Order;
use App\Repository\ProofTemplateRepository;
use App\Service\Admin\AutoGeneratedProofService;
use App\Service\StoreInfoService;
use DateTimeImmutable;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Dompdf\Dompdf;
use Dompdf\Options;
use Symfony\Bridge\Doctrine\Attribute\MapEntity;

class PdfController extends AbstractController
{
    public function __construct(
        private readonly StoreInfoService $storeInfoService,
    ) {}

    #[Route('/order-invoice/pdf/{orderId}', name: 'order_invoice_pdf', methods: ['GET', 'POST'])]
    public function index(Request $request, #[MapEntity(mapping: ['orderId' => 'orderId'])] Order $order, EntityManagerInterface $entityManager): Response
    {
        $storeName = $this->storeInfoService->getStoreName();
        $html = $this->render('emails/pdf/invoice.html.twig', [
            'order' => $order,
            'store_name' =>  $storeName,
        ]);

        $invoiceName = $order->getOrderId() . '_' . (new DateTimeImmutable())->format('YmdHis');

        $pdfOptions = new Options();
        $pdfOptions->set('isHtml5ParserEnabled', true);
        $pdfOptions->set('isRemoteEnabled', TRUE);
        $pdfOptions->set('isPhpEnabled', true);


        $dompdf = new Dompdf($pdfOptions);
        $dompdf->loadHtml($html);
        $dompdf->setPaper('A4', 'portrait');
        $dompdf->render();

        $output = $dompdf->output();

        // Return the PDF as a Response
        $response = new Response($output);
        $response->headers->set('Content-Type', 'application/pdf');
        $response->headers->set('Content-Disposition', 'inline; filename="' . $invoiceName . '.pdf"');

        return $response;
    }

    #[Route('/order-invoice-admin/pdf/{orderId}', name: 'order_invoice_admin_pdf', methods: ['GET', 'POST'])]
    public function orderInvoiceAdmin(#[MapEntity(mapping: ['orderId' => 'orderId'])] Order $order): Response
    {
        $storeName = $this->storeInfoService->getStoreName();
        $html = $this->render('emails/pdf/order_invoice_admin.html.twig', [
            'order' => $order,
            'store_name' =>  $storeName,
        ]);

        $invoiceName = $order->getOrderId() . '_' . (new DateTimeImmutable())->format('YmdHis');

        $pdfOptions = new Options();
        $pdfOptions->set('isHtml5ParserEnabled', true);
        $pdfOptions->set('isRemoteEnabled', TRUE);
        $pdfOptions->set('isPhpEnabled', true);


        $dompdf = new Dompdf($pdfOptions);
        $dompdf->loadHtml($html);
        $dompdf->setPaper('A4', 'portrait');
        $dompdf->render();

        $output = $dompdf->output();

        // Return the PDF as a Response
        $response = new Response($output);
        $response->headers->set('Content-Type', 'application/pdf');
        $response->headers->set('Content-Disposition', 'inline; filename="' . $invoiceName . '.pdf"');

        return $response;
    }

    #[Route('/orders/{orderId}/auto-generated-proof', name: 'order_auto_generated_proof')]
    public function autoGeneratedProof(
        Request $request,
        #[MapEntity(mapping: ['orderId' => 'orderId'])] Order $order,
        AutoGeneratedProofService $proofService
    ): Response {
        $withTemplate = $request->query->get('withTemplate');

        $withCustomerDesign = filter_var(
            $request->query->get('withCustomerDesign', false),
            FILTER_VALIDATE_BOOLEAN
        );

        ini_set('memory_limit', '1024M');
        ini_set('max_execution_time', '300');
        set_time_limit(300);

        try {
            $output = $proofService->generatePdf($order, $withTemplate, $withCustomerDesign);
            if (ob_get_length()) {
                ob_end_clean();
            }

            $pdfSize = strlen($output);

            $orderProofName = "order-proof-" . $order->getOrderId();
            $response = new Response($output);
            $response->headers->set('Content-Type', 'application/pdf');
            $response->headers->set('Content-Disposition', 'attachment; filename="' . $orderProofName . '.pdf"');
            $response->headers->set('Content-Length', (string)$pdfSize);

            return $response;
        } catch (\Throwable $e) {
            return new Response(
                'Failed to generate PDF: ' . $e->getMessage(),
                Response::HTTP_INTERNAL_SERVER_ERROR
            );
        }
    }
}
