<?php

namespace App\Service\Admin;

use App\Twig\AppExtension;
use Dompdf\Dompdf;
use Dompdf\Options;
use App\Entity\Order;
use App\Repository\ProofTemplateRepository;
use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;

class AutoGeneratedProofService extends AbstractController
{
    public function __construct(
        private ProofTemplateRepository $proofTemplateRepository,
        private AppExtension            $appExtension,
        private ParameterBagInterface   $params
    ) {}

    /**
     * Generate the auto-generated proof PDF binary.
     *
     * @param Order $order
     * @param bool  $withCustomerDesign — if true, skip templates
     *
     * @return string PDF binary
     */
    public function generatePdf(Order $order, ?string $withTemplate = null, bool $withCustomerDesign = false): string
    {
        if ($withTemplate === '1' || $withTemplate === null) {
            $proofTemplates = $this->proofTemplateRepository->fetchAll();
        } else {
            $proofTemplates = [];
        }

        if ($withCustomerDesign) {
            $this->convertImagesToBase64($order);
        }

        $html = $this->renderView('admin/order/auto-generated-proof/index.html.twig', [
            'order' => $order,
            'proofTemplates' => $proofTemplates,
            'withCustomerDesign' => $withCustomerDesign,
        ]);

        // Dompdf options
        $pdfOptions = new Options();
        $pdfOptions->set('isHtml5ParserEnabled', true);
        $pdfOptions->set('isRemoteEnabled', true);
        $pdfOptions->set('isPhpEnabled', false);
        $pdfOptions->set('fontDir', $this->params->get('kernel.project_dir') . '/public/proof-pdf-fonts');

        $dompdf = new Dompdf($pdfOptions);
        $dompdf->loadHtml($html);
        $dompdf->setPaper('A4', 'portrait');
        $dompdf->render();

        return $dompdf->output();
    }

    /**
     * Convert remote image URLs to base64 data URIs
     * This avoids Dompdf having to fetch images from CDN
     */
    public function convertImagesToBase64(Order $order): void
    {
        foreach ($order->getOrderItems() as $item) {
            $metaData = $item->getMetaData() ?? [];
            
            $designKeys = ['customerDesign', 'customerDesignProof'];
            $updated = false;

            foreach ($designKeys as $key) {
                if (!isset($metaData[$key])) continue;

                foreach ($metaData[$key] as $side => $url) {
                    if (empty($url)) continue;
                    
                    // Skip if already base64
                    if (strpos($url, 'data:image') === 0) continue;
                    
                    // Skip if not HTTP URL
                    if (strpos($url, 'http') !== 0) continue;

                    $base64Url = $this->appExtension->urlToBase64($url);
                    if ($base64Url !== $url) {
                        $metaData[$key][$side] = $base64Url;
                        $updated = true;
                    }
                }
            }

            if ($updated) {
                $item->setMetaData($metaData);
            }
        }
    }
}